---
release:
  top_down: true
  url: https://sourceforge.net/projects/reactos/files/ReactOS/0.4.14/
  iso_patterns:
    - '.*-release-.*\.iso'
    - '.*0\.4\.14\.iso'
rc:
  top_down: true
  url: https://sourceforge.net/projects/reactos/files/ReactOS/0.4.14/
  iso_patterns:
    - '.*-RC-.*\.iso'
nightly:
  top_down: false
  url: https://iso.reactos.org/bootcd/?C=M;O=A
  iso_patterns:
    - '.*-dev-.*-%{arch}.*\.iso'
