= Packer Qemu Builder for ReactOS

This is a an early version of my attempt to build KVM images from ReactOS ISOs.

== Prerequisites
* https://www.packer.io/[Packer] >= 1.7.0
* https://www.qemu.org/[Qemu] 
  (Tested with version 5.0.0 but older version should work as well)
* https://www.gnu.org/software/xorriso/[xorriso]
* 7z
* https://www.ruby-lang.org/[Ruby]
* https://github.com/ruby/rake[Rake]

== Howto

=== Download the images

NOTE: Currently only RC and nightly images work the boot CDs for `0.4.13`
      are bluescreening!

== Build images

=== Fully automated with `rake`

.Simple build with rake
[source,bash]
----
rake
----

.Build only nightly
[source,bash]
----
rake BUILD=nightly
----

TIP: With `rake` the environment variables `PACKER_LOG=1` and
     `PACKER_LOG_PATH=logs/reactos-<release>.log` will be set for better
     debugging.

.Clean up
[source,bash]
----
rake clean:all
----

Removes logs, os images and all but the most recent iso downloads.

.Clean logs
[source,bash]
----
rake clean:logs
----

.Clean images
[source,bash]
----
rake clean:images
----

.Clean ISO Files
[source,bash]
----
rake clean:isos
----

=== Manual build

* Download the zipped ISO images from the respective websites, unpack them to
  the `iso/reactos` directory.

* Further checksum them with `sha256sum` and modify the values in the
  `reactos-<release>.pkrvars.hcl` files.

* Inject a modified the `unattend.inf` file into the iso as outlined
  https://gist.github.com/uroesch/49d729fb5c86ed54974c0bca50873761[here].

.Simple build manually
[source,bash]
----
packer build -var-file="reactos-rc.pkrvars.hcl" \
  -only="*.reactos-rc" reactos.pkr.hcl
packer build -var-file="reactos-nightly.pkrvars.hcl" \
  -only="*.reactos-nightly" reactos.pkr.hcl
----

== Known issues

* Release candidate builds are currently using 0.4.14-RC releases the 0.4.15 
  RC are not yet online.
* The nightly x64 (0.4.15) are building a working image but the finished
  machine is still quite buggy.
* Occasionally the nightly builds won't work as expected. As it is always on
  the latest commit some bumps in the road are to be expected.

== Todo
* [ ] Install `virtio` drivers

// vim: set colorcolumn=80 textwidth=80 spell spelllang=en_us :
