# -----------------------------------------------------------------------------
# Run nightly build verification
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.2.0
# -----------------------------------------------------------------------------
name: nightly-build

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - main
  schedule:
    - cron: '13 4 * * *' # Sync submodules daily
  workflow_dispatch:

jobs:
  nightly-build:
    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest

    steps:
    - name: Install qemu and xorriso
      shell: bash
      run: >
        sudo apt-get -y update &&
        sudo apt-get -y install qemu-system-x86 qemu-utils xorriso

    - name: Packer version
      shell: bash
      run: packer -version

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build nightly
      shell: bash
      run: >
        rake
        BUILD=reactos-nightly
        TARGET=x86
        FAIL_FAST=true
        PACKER_LOG_PATH=build.log
        PKR_VAR_headless=true

    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: debug.zip
        path: build.log 
