# -----------------------------------------------------------------------------
# Run nightly build verification
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.3.1
# -----------------------------------------------------------------------------
name: nightly-build

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - main
  schedule:
    - cron: '13 4 * * *' # Sync submodules daily
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: uroesch/packer:1.3.1
    strategy:
      fail-fast: true
      matrix:
        build:
          - reactos-nightly
        builder:
          - qemu
        arch:
          - x86
          # - x64 doesn't always not build 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build nightly
      shell: bash
      run: >
        rake
        BUILD=${{ matrix.build }}
        BUILDER=${{ matrix.builder }}
        ARCH=${{ matrix.arch }}
        HEADLESS=true
        FAIL_FAST=true
        PACKER_LOG_PATH=build.log

    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: debug.zip
        path: build.log

    - name: Upload qcow image
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.build }}-${{ matrix.arch }}
        path: images/*.qcow2
